games/data/lethal-company.yml
Added the following labels:
- Client-side
- Server-side
=> Add client & server-side labels

games/data/lethal-company.yml
Added some labels some people from the modding community requested.
=> Add community label requests

games/data/lethal-company.yml
Added an "Interiors" tag for Lethal Company.
=> Additional tag for lethal-company.yml

games/data/content-warning.yml
Updated content-warning.yml @ request of @MaxWasUnavailable
=> Update Content Warning Categories and Sections

games/data/against-the-storm.yml, games/data/lycans.yml, games/data/vertigo-2.yml
Against the Storm
Lycans
Vertigo 2
refs -
=> Add 3 games

games/data/content-warning.yml
=> [VITAL] Fixed failing build.

games/data/panicore.yml
=> Update Panicore Discord link

games/data/distance.yml, games/data/five-nights-at-freddys-into-the-pit.yml, games/data/tank-team.yml, games/data/the-choicer-voicer.yml, games/data/zelda-64-recompiled.yml
Distance
FNAF into the pit
Tank Team
The Choicer Voicer
Zelda 64 Recompiled
=> Add 5 games

games/data/void-crew.yml
Add categories and external links. Based on PR #70 by @Nagord.
=> Update Void Crew

games/data/2-ship-2-harkinian.yml, games/data/ship-of-harkinian.yml, games/data/starship.yml
* Starship
* 2 Ship 2 Harkinian
* Ship of Harkinian
=> Add 3 new communities (Harbour Masters' PC ports)

games/data/my-dream-setup.yml
Add BepInEx-BepInExPack to autolistPackageIds
=> Autolist BepInExPack in My Dream Setup community

games/data/gatekeeper.yml, games/data/pulsar-lost-colony.yml, games/data/songs-of-conquest.yml, games/data/white-knuckle.yml
* Gatekeeper
* Pulsar: Lost Colony
* Songs of Conquest
* White Knuckle
=> Add 4 new games

games/src/models.ts, games/src/schema/validator.ts
Define all fields of the r2modman object and change some strings to enums with known values.
=> Improve JSON schema

games/data/monster-train-2.yml
- Added Clans label
- Updated Game App ID from demo to full game.
=> Updated Monster Train 2

games/data/peak.yml
Added the following: World, Items, Quality Of Life, Client Side, Host Only, All Clients, Translations, Optimization
=> Added relevant tags to PEAK.yml

games/data/mycopunk.yml
`Sandbox` category is meant to allow users to upload cheat-like mods while making sure such mods won't affect other users 
https://discord.com/channels/809128887366975518/1395754498785415312/1397328889457545268
=> Add `Sandbox` category as for game developer request

games/data/resonite.yml, games/misc/modloader-packages.yml, games/src/models.ts, games/src/schema/packageLoaders.ts
This is a BepInEx spinoff tailored to support the gme Resonite.
=> Add BepisLoader

games/data/generated/shadows-of-doubt.yml, games/data/house-of-legacy.yml, games/data/super-mario-3d-world.yml
* Shadows of Doubt GOG support
* HK: Silksong GOG support
* House of Legacy Steam support
* Super Mario 3D World (just the community)
=> New game supports added

games/data/atlyss.yml
That's all I can really add to Atlyss thunderstore page.
=> Add Quest Category

games/data/hollow-knight-silksong.yml
Add Mac/Linux executable names
=> Add other executable names for Silksong
